### ISSUE TITLE
Issues with crosstab

### ISSUE THREAD

**Issue by silzila** [silzila/silzila#33]
issue 1
drag and drop order_date to row and then again to column - it will break

issue 2
drag quantity to row or column - it is integer.
if you drop quantity to measure then the dim becomes floating point

feature
if you drag and drop order_date to dimension then column name should be year of order_date and if user changes timeGrain to month then column name should be month of order_date

feature/bug
current version doesn't have col header or row header when only column is there but no row is added.

**Comment by silzila** [comment]
Expected for issue 1:
row should be year of order_date and column should be year of order_date(2)

**Comment by Jeeva-SJKPY** [comment]
Closing the bug, hence it is resolved
